name: Inject Firebase Config

on:
  push:
    branches:
      - main  # Run on every push to main

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Config File
        run: |
          cat <<EOF > config.js
          const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
          };
          export default firebaseConfig;
          EOF

      - name: Commit and Push Config File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add config.js
          git commit -m "Update Firebase config [skip ci]" || echo "No changes to commit"
          git push
