name: Update Operator Image Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once per day at midnight UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  fetch-operator-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Operator Image Data
        run: |
          curl -s "https://api.github.com/repos/ArknightsAssets/ArknightsAssets/git/trees/34c7fc91e3192187a8763ca98e9a782668ec23fe?recursive=1" > data.json
          jq -r '.tree[] | select(.path | test("arts/characters/.+\\.png$")) | .path' data.json > images.txt

          python3 <<EOF
          import json

          # Load operator name mappings
          import urllib.request
          name_mapping_url = "https://raw.githubusercontent.com/PuppiizSunniiz/AN-EN-Tags/main/py/dict.json"
          with urllib.request.urlopen(name_mapping_url) as response:
              name_data = json.load(response)["Char"]["Code2Name"]

          # Load image paths
          with open("images.txt") as f:
              image_paths = [line.strip() for line in f.readlines()]

          # Organize images by operator
          operator_images = {}
          for path in image_paths:
              operator_id = path.split("/")[3]  # Extract operator ID from path
              if operator_id in name_data:
                  operator_images.setdefault(operator_id, {"name": name_data[operator_id], "images": []})
                  operator_images[operator_id]["images"].append(f"https://raw.githubusercontent.com/ArknightsAssets/ArknightsAssets/main/assets/torappu/dynamicassets/{path}")

          # Save to JSON
          with open("operators.json", "w") as f:
              json.dump(operator_images, f, indent=2)

          print(f"Processed {len(operator_images)} operators.")
          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add operators.json
          git commit -m "Updated operator images" || echo "No changes to commit"
          git push
